apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:afba2f932b1c5e359835d2b60aa242be42949a042f6fae6e84606194a110269d
  name: quay.io/rh-ee-srehman/nodejs
  newName: quay.io/rh-ee-srehman/nodejs
