apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:a811c13a77e5bc37945c4e6a9b56be8389133903ed1e49ef95e77c42fafa44aa
  name: quay.io/rh-ee-srehman/nodejs
  newName: quay.io/rh-ee-srehman/nodejs
