apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:4c20fa4ee29f3450bed87529207169ffc74a2f305c374ff4677bd97ae67138ae
  name: quay.io/rh-ee-srehman/nodejs
  newName: quay.io/rh-ee-srehman/nodejs
